---
title: "PCA plots"
author: "Katie Lotterhos"
date: "10/2/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

## PCA based on thinned SNP set


```{r thinned, fig.width=8, fig.height=28, fig.fullwidth=TRUE}
# load data
pcthinned <- readRDS("50kRandomSubsetThinned13PCs.rds")
str(pcthinned)
thinnedSNPs <- read.table("allLociLocationsAfterThinning13PCs.txt")
head(thinnedSNPs)

# load individual data
ind0 <- read.csv("modified_samplemetadata.csv")
head(ind0)
str(ind0)


ind_order <- read.table("ind_order_vcf.txt")
colnames(ind_order) <- "Sample.ID"
ind_order <- data.frame(ind_order, pcthinned$u)
str(ind_order)

identical(ind0$Sample.ID, ind_order$Sample.ID)

data.frame(sort(ind0$Sample.ID), sort(ind_order$Sample.ID))

ind <- merge(ind_order, ind0, by="Sample.ID", all.x=TRUE, all.y=TRUE)
# check that 90 observations

levels(ind$custom.id)
ind <- ind[order(ind$custom.id),]
ind$pch <- as.numeric(ind$custom.id)
str(ind)
head(ind)
```

# Scree plot of PCaxes
```{r}
layout(c(1))
par(mar=c(4,4,1,1))
plot(pcthinned$d, xlab="PC", ylab= "Variation explained", bty="l")
```

# Plot scores of individuals
```{r}
alph <- 0.8
plotdf <- data.frame(custom.id=unique(ind$custom.id), 
                pch = unique(ind$pch),
                color = unique(ind$color),
                plot.id = unique(ind$plot.id))
  #this should keep things in order

head(plotdf)


layout(matrix(c(1,2), ncol=2),  widths = c(1,0.7)) 
par(mar=c(4,4,1,1))
plot(ind$X1, ind$X2,
     xlab = "PC 1", ylab= "PC 2", 
     pch = ind$pch, 
     col = adjustcolor(as.character(ind$color), alpha=alph), bty="l")
par(mar=c(0,0,0,0))
plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n",
     xlab="", ylab="")
legend("center", legend = plotdf$plot.id,  horiz = FALSE, inset = c(0, 0), bty = "n", pch = plotdf$pch, 
    col = adjustcolor(as.character(plotdf$color),alph), cex=1 )

layout(matrix(c(1,2), ncol=2),  widths = c(1,0.7)) 
par(mar=c(4,4,1,1))
plot(ind$X1, ind$X3,
     xlab = "PC 1", ylab= "PC 3", 
     pch = ind$pch, 
     col = adjustcolor(as.character(ind$color), alpha=alph), bty="l")
par(mar=c(0,0,0,0))
plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n",
     xlab="", ylab="")
legend("center", legend = plotdf$plot.id,  horiz = FALSE, inset = c(0, 0), bty = "n", pch = plotdf$pch, 
    col = adjustcolor(as.character(plotdf$color),alph), cex=1 )

layout(matrix(c(1,2), ncol=2),  widths = c(1,0.7)) 
par(mar=c(4,4,1,1))
plot(ind$X4, ind$X3,
     xlab = "PC 4", ylab= "PC 3", 
     pch = ind$pch, 
     col = adjustcolor(as.character(ind$color), alpha=alph), bty="l")
par(mar=c(0,0,0,0))
plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n",
     xlab="", ylab="")
legend("center", legend = plotdf$plot.id,  horiz = FALSE, inset = c(0, 0), bty = "n", pch = plotdf$pch, 
    col = adjustcolor(as.character(plotdf$color),alph), cex=1 )
```

```{r, echo=FALSE, eval=FALSE}
# Can use to produce pdf

par(oma=c(0,0,0,0))
layout(matrix(c(1,2,3,4,4,4), ncol=2), widths = c(1,0.7),
       heights = c(1,1), respect = FALSE)
par(mar=c(4,4,1,1))
plot(ind$X1, ind$X2,
     xlab = "PC 1", ylab= "PC 2", 
     pch = ind$pch, 
     col = adjustcolor(as.character(ind$color), alpha=alph), bty="l", cex=1.5)

plot(ind$X1, ind$X3,
     xlab = "PC 1", ylab= "PC 3", 
     pch = ind$pch, 
     col = adjustcolor(as.character(ind$color), alpha=alph), bty="l", cex=1.5)

plot(ind$X4, ind$X3,
     xlab = "PC 4", ylab= "PC 3", 
     pch = ind$pch, 
     col = adjustcolor(as.character(ind$color), alpha=alph), bty="l")


par(mar=c(0,0,0,0))
plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n",
     xlab="", ylab="")
legend("center", legend = plotdf$plot.id,  horiz = FALSE, inset = c(0, 0), bty = "n", pch = plotdf$pch, 
    col = adjustcolor(as.character(plotdf$color),alph), cex=1 )
```

# Zoom in on regions of PC1

### Zoom in on PC1 vs PC2 left side
```{r}
layout(matrix(c(1,2), ncol=2),  widths = c(1,0.7)) 
par(mar=c(4,4,1,1))
plot(ind$X1, ind$X2,
     xlab = "PC 1", ylab= "PC 2", 
     pch = ind$pch, 
     col = adjustcolor(as.character(ind$color), alpha=alph), bty="l",
     xlim=c(-0.2, -0.07),
     ylim=c(-0.06, 0.05))
par(mar=c(0,0,0,0))
plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n",
     xlab="", ylab="")
legend("center", legend = plotdf$plot.id,  horiz = FALSE, inset = c(0, 0), bty = "n", pch = plotdf$pch, 
    col = adjustcolor(as.character(plotdf$color),alph), cex=1 )
```

### Zoom in on 1 vs 2 middle
```{r}
layout(matrix(c(1,2), ncol=2),  widths = c(1,0.7)) 
par(mar=c(4,4,1,1))
plot(ind$X1, ind$X2,
     xlab = "PC 1", ylab= "PC 2", 
     pch = ind$pch, 
     col = adjustcolor(as.character(ind$color), alpha=alph), bty="l",
     xlim=c(-0.05, 0.1),
     ylim=c(0, 0.15))
par(mar=c(0,0,0,0))
plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n",
     xlab="", ylab="")
legend("center", legend = plotdf$plot.id,  horiz = FALSE, inset = c(0, 0), bty = "n", pch = plotdf$pch, 
    col = adjustcolor(as.character(plotdf$color),alph), cex=1 )
```
### Zoom in on 1 vs 3 right side
```{r }
layout(matrix(c(1,2), ncol=2),  widths = c(1,0.7)) 
par(mar=c(4,4,1,1))
plot(ind$X1, ind$X2,
     xlab = "PC 1", ylab= "PC 2", 
     pch = ind$pch, 
     col = adjustcolor(as.character(ind$color), alpha=alph), bty="l",
     xlim=c(0.05, max(ind$X1)))
par(mar=c(0,0,0,0))
plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n",
     xlab="", ylab="")
legend("center", legend = plotdf$plot.id,  horiz = FALSE, inset = c(0, 0), bty = "n", pch = plotdf$pch, 
    col = adjustcolor(as.character(plotdf$color),alph), cex=1 )

```
