---
title: "PCA plots"
author: "Katie Lotterhos"
date: "10/2/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

## PCA based on thinned SNP set


```{r thinned, fig.width=8, fig.height=8}
# load data
pcthinned <- readRDS("fullDatasetThinned13PCs.rds")
ls()
str(pcthinned)
thinnedSNPs <- read.table("allLociLocationsAfterThinning13PCs.txt")
head(thinnedSNPs)

# load individual data
ind <- read.csv("modified_samplemetadata.csv")
head(ind)
str(ind)
ind$pch <- as.numeric(ind$plot.id)
levels(ind$custom.id)
ind <- ind[order(ind$custom.id),]
head(ind)

# Plot scores of individuals
alph <- 0.8
par(oma=c(0,0,0,0))
layout(matrix(c(1,2,3,3), ncol=2), widths = c(1,0.7),
       heights = c(1,1), respect = FALSE)
par(mar=c(4,4,1,1))
plot(pcthinned$u[,1], pcthinned$u[,2],
     xlab = "PC 1", ylab= "PC 2", 
     pch = ind$pch, 
     col = adjustcolor(as.character(ind$color), alpha=alph), bty="l", cex=1.5)
plot(pcthinned$u[,1], pcthinned$u[,3],
     xlab = "PC 1", ylab= "PC 3", 
     pch = ind$pch, 
     col = adjustcolor(as.character(ind$color), alpha=alph), bty="l", cex=1.5)


plotdf <- data.frame(custom.id=unique(ind$custom.id), 
                pch = unique(ind$pch),
                color = unique(ind$color),
                plot.id = unique(ind$plot.id))
head(plotdf)
par(mar=c(0,0,0,0))
plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n",
     xlab="", ylab="")
legend("center", legend = plotdf$plot.id,  horiz = FALSE, inset = c(0, 0), bty = "n", pch = plotdf$pch, 
    col = adjustcolor(as.character(plotdf$color),alph), cex=1 )
```

```{r}
layout(matrix(c(1,2), ncol=2),  widths = c(1,0.7)) 
par(mar=c(4,4,1,1))
plot(pcthinned$u[,3], pcthinned$u[,4],
     xlab = "PC 3", ylab= "PC 4", 
     pch = ind$pch, 
     col = adjustcolor(as.character(ind$color), alpha=alph), bty="l")
par(mar=c(0,0,0,0))
plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n",
     xlab="", ylab="")
legend("center", legend = plotdf$plot.id,  horiz = FALSE, inset = c(0, 0), bty = "n", pch = plotdf$pch, 
    col = adjustcolor(as.character(plotdf$color),alph), cex=1 )

### Zoom in on 1 vs 3
layout(matrix(c(1,2), ncol=2),  widths = c(1,0.7)) 
par(mar=c(4,4,1,1))
plot(pcthinned$u[,1], pcthinned$u[,3],
     xlab = "PC 1", ylab= "PC 3", 
     pch = ind$pch, 
     col = adjustcolor(as.character(ind$color), alpha=alph), bty="l",
     xlim=c(-0.2, -0.07),
     ylim=c(-0.1,0.1))
par(mar=c(0,0,0,0))
plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n",
     xlab="", ylab="")
legend("center", legend = plotdf$plot.id,  horiz = FALSE, inset = c(0, 0), bty = "n", pch = plotdf$pch, 
    col = adjustcolor(as.character(plotdf$color),alph), cex=1 )

### Zoom in on 1 vs 3
layout(matrix(c(1,2), ncol=2),  widths = c(1,0.7)) 
par(mar=c(4,4,1,1))
plot(pcthinned$u[,1], pcthinned$u[,3],
     xlab = "PC 1", ylab= "PC 3", 
     pch = ind$pch, 
     col = adjustcolor(as.character(ind$color), alpha=alph), bty="l",
     xlim=c(-0.17, -0.15),
     ylim=c(0.03,0.04))
par(mar=c(0,0,0,0))
plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n",
     xlab="", ylab="")
legend("center", legend = plotdf$plot.id,  horiz = FALSE, inset = c(0, 0), bty = "n", pch = plotdf$pch, 
    col = adjustcolor(as.character(plotdf$color),alph), cex=1 )

### Zoom in on 1 vs 3
layout(matrix(c(1,2), ncol=2),  widths = c(1,0.7)) 
par(mar=c(4,4,1,1))
plot(pcthinned$u[,1], pcthinned$u[,3],
     xlab = "PC 1", ylab= "PC 3", 
     pch = ind$pch, 
     col = adjustcolor(as.character(ind$color), alpha=alph), bty="l",
     xlim=c(0.04, 0.1),
     ylim=c(-0.11,0))
par(mar=c(0,0,0,0))
plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n",
     xlab="", ylab="")
legend("center", legend = plotdf$plot.id,  horiz = FALSE, inset = c(0, 0), bty = "n", pch = plotdf$pch, 
    col = adjustcolor(as.character(plotdf$color),alph), cex=1 )

### Zoom in on 1 vs 3
layout(matrix(c(1,2), ncol=2),  widths = c(1,0.7)) 
par(mar=c(4,4,1,1))
plot(pcthinned$u[,1], pcthinned$u[,3],
     xlab = "PC 1", ylab= "PC 3", 
     pch = ind$pch, 
     col = adjustcolor(as.character(ind$color), alpha=alph), bty="l",
     xlim=c(0.04, 0.15),
     ylim=c(0,0.4))
par(mar=c(0,0,0,0))
plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n",
     xlab="", ylab="")
legend("center", legend = plotdf$plot.id,  horiz = FALSE, inset = c(0, 0), bty = "n", pch = plotdf$pch, 
    col = adjustcolor(as.character(plotdf$color),alph), cex=1 )
```
