library(qvalue)
library(lfmm)
########################################################################
# 
# File    : LFMMwild.R
# History : 2019/03/20 Created by Kevin Freeman (KF) 
# 
#----------------------------------------------------------------------
# This script is used to perform LFMM ridge analysis  for association 
# between genotype and environmental factors in wild type populations. 
# It starts with  a genotype matrix generated by Bodie with 
# populationStructureScript.R and subsets it to only include wild type
# populations
#########################################################################
# setwd("/media/kevin/TOSHIBA_EXT/LOTTERHOS_LAB/OysterGenomeProject/popstructureOutliers")
### Read in RDS and metadata
# allData        <- readRDS("data/large_data/genotypeMatrix.rds")
print("Reading and processing metadata")
metadata       <- read.csv("data/modified_samplemetadata.csv", stringsAsFactors = FALSE, header = TRUE)
envi_metadata  <- read.csv("data/environment/full_sample_metadata_4_20_19_ER.csv", stringsAsFactors = FALSE, header = TRUE)

# make the Wild.Sel column match between the two metadata files
envi_metadata$Wild.Sel[which(envi_metadata$Wild.Sel == "inbred")] <- "I"

# combine the two metadata csv files
# NG_H0H4 is dropped because it is only in modified_samplemetadata.csv
# LM_2 is dropped because it is only in full_sample_metadata_4_20_19_ER.csv
common_cols <- intersect(names(envi_metadata), names(metadata))
common_cols <- common_cols[! common_cols %in% c("NOTES", "Ecotype", "Sex")]  # remove columns that don't have same info b/w files
comb_metadata <- merge(metadata, envi_metadata, by = common_cols)

# ### Select only Wild populations to rewrite matrix
#wild        <- allData
#wild$G      <- allData$G[, which(comb_metadata$wild_for_assoc == 1)]
#wild$Pop.ID <- metadata$Pop.ID[which(comb_metadata$wild_for_assoc == 1)]
# 
# # The genotype matrix has some fixed values, remove them before proceeding
#variances <- apply(wild$G, 1, var)
#not_fixed <- variances > 0
#wild$G <- wild$G[not_fixed, ]
#  update the positions and chr
#wild$Pos <- wild$Pos[not_fixed]
#wild$Chr <- wild$Chr[not_fixed]
# 
# ### Save the new genotype matrix just in case
#saveRDS(wild, paste("data", "genotypeMatrix_selecting_Wild.rds", sep="/"))
print("plotting PCA scree plot")
wild <- readRDS("data/genotypeMatrix_selecting_Wild.rds")
png("PCA_scree_plot.png")
PCA <- prcomp(wild$G)
plot(PCA, type = "l", main = "PCA Scree Plot")
dev.off()


calcEnviLFMMandSpRho <- function(envi_var, pop_object){
  # scale genotype matrix
  scaled.genotype <- scale(as.matrix(t(pop_object$G)))
  # create a temperature matrix
  envi        <- comb_metadata[envi_var]
  envi        <- envi[which(comb_metadata$wild_for_assoc == 1), ]
  envi_matrix <- matrix(data = envi, nrow = length(envi), ncol = 1)
  scaled.envi <- scale(envi_matrix)
  
  # build lfmm ridge model
  print("Building lfmm ridge model")
  lfmm.ridge <- lfmm::lfmm_ridge(Y = scaled.genotype, X = scaled.envi, K = 3, lambda = 1e-4)
  # perform association testing
  print("Running lfmm test")
  lfmm.test.ridge <- lfmm::lfmm_test(Y = scaled.genotype, X = scaled.envi, lfmm = lfmm.ridge, calibrate = "gif")
  
  # save the ridge objects
  print("Saving lfmm objects")
  saveRDS(lfmm.ridge, paste("data", "lfmm_ridge_results_mean_annual_temp.rds", sep = "/"))
  saveRDS(lfmm.test.ridge, paste("data", "lfmm_ridge_test_results_mean_annual_temp.rds", sep = "/"))

  # read in ridge objects
  #lfmm.ridge      <- readRDS("data/lfmm_ridge_results_mean_annual_temp.rds")
  #lfmm.test.ridge <- readRDS("data/lfmm_ridge_test_results_mean_annual_temp.rds")
  
  # get p values
  p.values.ridge <- lfmm.test.ridge$calibrated.pvalue
  print(c("lfmm.test.ridge$gif", lfmm.test.ridge$gif))
  
  # plots
  #hist(p.values.ridge, col = "lightgreen", main="LFMM ridge")
  #qval <- qvalue::qvalue(p.values.ridge)
  #plot(qval)
  print("Plotting LF 1 and 2")
  png(paste("figures/6envi_assoc/LFMM_ridge_0.0", envi_var, "LF_plot.png", sep = "_"))
  plot(lfmm.ridge$U[,1], lfmm.ridge$U[,2], col = comb_metadata[which(comb_metadata$wild_for_assoc == 1),]$color, pch = 19, 
       main = paste("LFMM Ridge", envi_var,"Association"), xlab = "LF1", ylab = "LF2")
  text(lfmm.ridge$U[,1], lfmm.ridge$U[,2] + 10, labels = pop_object$Pop.ID, cex = 0.6)
  dev.off()
  rm(lfmm.test.ridge)
  rm(lfmm.ridge)
 
  LFMM_ridge_0.0_log10p <- -log10(as.numeric(p.values.ridge))
  rm(p.values.ridge)
  # LFMM plot
  png(paste("figures/6envi_assoc/LFMM_ridge_0.0", envi_var, "pvalues_plot.png", sep = "_"))
  plot(pop_object$Pos, LFMM_ridge_0.0_log10p, main = "LFMM Ridge P-values")
  dev.off()
  
  
  # spearman's correlation
  print("Calculating spearman's correlation")
  absSpCor <- abs(cor(scaled.envi, scaled.genotype, method = "spearman"))
  png(paste("figures/6envi_assoc/Spearmanns_vs_LFMM", envi_var, "plot.png", sep = "_"))
  plot(absSpCor, LFMM_ridge_0.0_log10p, main = "Spearmann's Rho vs LFMM Ridge")
  abline(lm(LFMM_ridge_0.0_log10p ~ as.vector(absSpCor)), col = "red")
  dev.off()
  
  unique_ID <- sprintf("%02d_%09d", pop_object$Chr, pop_object$Pos)
  print("Creating data frame")

  print("making matrix")
  stat_matrix <- matrix(c(pop_object$Pos, pop_object$Chr, unique_ID, 
		     LFMM_ridge_0.0_log10p, absSpCor), ncol = 5, nrow = length(unique_ID))
  print("matrix to data frame")
  out_table <- as.data.frame(stat_matrix)

  print(str(out_table))
  print("Naming data frame") 
  colnames(out_table) <- c("pos", "chr", "unique", paste("LFMM_ridge_0.0_log10p", envi_var, sep = "_"),
                         paste("Spearmanns_Rho_ABS", envi_var, sep = "_"))
  print("saving dataframe")
  write.table(out_table, file = paste0("data/envi_assoc_results/", envi_var, "_assoc_results.txt"), 
               quote = FALSE, sep = "\t", row.names = FALSE)
}

calcEnviLFMMandSpRho(envi_var = "Mean_Annual_Temperature_Celsius", pop_object = wild)

